---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      initContainers:
      - name: install-plugins
        image: iailyas/my-grafana:1.0.0 ##['sh', '-c', 'grafana-cli plugins install alexanderzobnin-zabbix-app'] 
        command: ['ls']  #&& cp -r /var/lib/grafana/plugins /var/lib/grafana/data/plugins 
      containers:
        - name: grafana
          image: iailyas/my-grafana:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http-grafana
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /robots.txt
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            tcpSocket:
              port: 3000
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 250m
              memory: 750Mi
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
      name: http-grafana
  selector:
    app: grafana
  sessionAffinity: None
  type: LoadBalancer



  #   kubectl create configmap grafana-plugins --from-file=/path/to/your/directory --namespace=my-grafana
#  kubectl create namespace my-grafana
