apiVersion: v1
kind: Namespace
metadata:
  name: zabbix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix-ui
  namespace: zabbix
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  # Use the host you used in your kubernetes Ingress Configurations
  - host: zabbix.example.com
    http:
      paths:
      - backend:
          service:
            name: zabbix-web
            port:
              number: 8080
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - zabbix.apps
    secretName: zabbix-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-secret
  namespace: zabbix
data:
# USe base64 in the certs
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURFVENDQWZrQ0ZEd0xBWnE4ajFIU0tHdG5kVkxIbjkxMjlnZjFNQTBHQ1NxR1NJYjNEUUVCQ3dVQU1FVXgKQ3pBSkJnTlZCQVlUQWtGVk1STXdFUVlEVlFRSURBcFRiMjFsTFZOMFlYUmxNU0V3SHdZRFZRUUtEQmhKYm5SbApjbTVsZENCWGFXUm5hWFJ6SUZCMGVTQk1kR1F3SGhjTk1qVXdNVEUyTURZeU1UTTVXaGNOTXpVd01URTBNRFl5Ck1UTTVXakJGTVFzd0NRWURWUVFHRXdKQlZURVRNQkVHQTFVRUNBd0tVMjl0WlMxVGRHRjBaVEVoTUI4R0ExVUUKQ2d3WVNXNTBaWEp1WlhRZ1YybGtaMmwwY3lCUWRIa2dUSFJrTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQwpBUThBTUlJQkNnS0NBUUVBOFlQQU4rTW9CNGJxcml2bHJ0Y3ZqdSt2L2UzckMrYWI1c2ZBMXVaczF0NVFybUsrClpWRC9uVUY4YjQyVlQ1aUlGTFZSYXBzNHpLY1pHcHZLaTVnSXlBVTNJUlNmRlFQdS9UU3phK1ZTaWsxcUhXR3IKUGNtdnVZaGlBaFlYSXljQVVhKytvT3c3QTVsQnlYT3NqbGNsKzV1REN1QjIvQlF3a2RXOURuY2hjYVlMSzJkRApaYzNtVkt2a1pBN1hJR3dDWitldWxkRFBtM3d0U1hWeTdYRUFuWlZlMTVVOUJhUWw3d0lyZU1YaHE4OXA1andSCit6VVRITm1pWUFIdXhwbGY2QzZsKzMxT1dXMnpuaU9PTUYyZzFScnFySTlsQU93ZmEwQlRYY1lxWXJQQm81OFEKcGovOVFkUTBxWGFMWkhlZ1dxZEpJeWNFYjYyL0ttL204UE1BSVFJREFRQUJNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFCdkVuSGhUSFk1R01vNTJFN3FaaHZRRUZURUNUc1JRY0NOcEQ0QmlZMHkxamxxNWZTUGhFR3dkZ3lqCjBGTktUSEtqL0I5bEhrN0JyL21oRFN4VGg0dzhGclIzeFczek42OGpRRER2amlBdFpWTVY2NFppSEh4VDNFeUgKYWM0ZFBMSGUxTVJPRXZWQmZTQWs3NGxBSGtlNmdvTVNGZmFCU2p6OW4wRTRjS0pCdkpJSE5TQ2Q4aUtqb0M3bgo1bVFNeE9PRjdIM21wVEF6NnRPRkFsaGlhNVQ3Z0FKdjhFUndDaW5hL0pHM01lSjRPaDFDYnJVNkdyMGdISmFtCmhvNUVrNzFUdjR4NzljVDhxQnc0OWRhUzIySWdKWHJjWU0yN3pMVytyQTBHaDMzK1dWWXd6bk5SUFllT1EyY3YKbFY4bnUzV3dTOWdKcGIxYU9WZlJveXlnVjRRNQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2QUlCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktZd2dnU2lBZ0VBQW9JQkFRRHhnOEEzNHlnSGh1cXUKSytXdTF5K083Ni85N2VzTDVwdm14OERXNW16VzNsQ3VZcjVsVVArZFFYeHZqWlZQbUlnVXRWRnFtempNcHhrYQptOHFMbUFqSUJUY2hGSjhWQSs3OU5MTnI1VktLVFdvZFlhczl5YSs1aUdJQ0ZoY2pKd0JScjc2ZzdEc0RtVUhKCmM2eU9WeVg3bTRNSzRIYjhGRENSMWIwT2R5RnhwZ3NyWjBObHplWlVxK1JrRHRjZ2JBSm41NjZWME0rYmZDMUoKZFhMdGNRQ2RsVjdYbFQwRnBDWHZBaXQ0eGVHcnoybm1QQkg3TlJNYzJhSmdBZTdHbVYvb0xxWDdmVTVaYmJPZQpJNDR3WGFEVkd1cXNqMlVBN0I5clFGTmR4aXBpczhHam54Q21QLzFCMURTcGRvdGtkNkJhcDBrakp3UnZyYjhxCmIrYnc4d0FoQWdNQkFBRUNnZ0VBRjlLZnBNT2U0TE14dGZGMWkvd0U0R3dMSjVpT3pWTTNnSm1tajJ3V1ExR1YKa3NZQnN0dTlBd1dCSVQzTmd4YndJVjdMUTZGQkJvcmJBcEZvZHNHTjZERC9nWjlYbThxU0NkN25iZGFtZ0Nibgp0ek01b1hRaUJjS0tyRnNDZUVDeUd0eWppSnNVclNPeVpnMG5jYmp0OGJZaXhIRmt1elBBb0xuOUZvNnd1VlZ2CkJ6RHNEM2FGcnhoYTc4RzRsSmVyMzgyNGlwVmlkQ0JZRkREbFhMcDJvNE9jalVyL1lDaW5kZ1I5d1BBRjFEcEIKeFlSWFcwaGpCYkJSVU9CN25CMDdjRk5oM3hTanZWRm5NenBNLzEwSFRlQ1loZE9FeUxDbjFvdzhBSTI5dG54MwpmRTFqRmpFaU1SWjk0ajREQjVicXIvbU9SeDVmUlNVK25XMzc2dlluR1FLQmdRRDlzM0IvZUpFVzV3ekluaEw5CkEzcDBlejJCWHdnZC9NbDNPU2tmSzg5T0MreEpMTTN3S29iTzZkMWkwYmlLSWE5aXZCNUl1Vmc4d1lpeERUM0EKRGR0VnYrWktxL3V1NUt6bkgxbGN4K1c5QXhhbnBhbUlCeHBxTzBOVC82UDZzMng1eEdFbm1VSS9CZ3UxQnBUZQpaR2JmcDFCZ0ZrZU1LbklpYjlGVDBENGVQUUtCZ1FEenRBcGJta3BKM3Bud2R5SFY4VXNjOXNKYjdsWkpEYVhrClpUUVczWFZLVng3VjFaQzVON05Jc3BQa3B6Z281a3IwbExLY2dOdW9NdWpwTW9vSGRCbTJzamc3Tnl2UW1qck8KOXhQWGZOeWJzT29NeSs0MjhOb2FIMEVIcHhhcjhYdnBWWVBVZzduSzVhVGI0SlY1RDBZNUNEdnpzaTVSMFRpdwo5VWpELzFjTHRRS0JnRUNSOHdmK2Y2NzhqMXhnSHlVV1JZeHY4VytENkdUNWVhMUdkeGpmNVp0UG5ZdmlRMmZrCjZ2cXV1eEh6bnF4SmRvSUNyeEtEV2RuY3lCV0g4VGQ0VDJLN3ZMazBuSkllMFlMaGo3VDFpNXRYdGVSbFhZaXAKaGllVGZjZGJRVGtGZ1k1Y1ZQM25HOTAraEt4R1NJMXhzRjBzRUdEa1NzRjU3Q0tub3ZkYUFQVmhBb0dBSE1Kawpib2I0dVZyeG83VUxZeW9FaVRoOW0wZTNHd3ZuUmRyRG1PY3Rqa1pWdHpwcXg5RFE4WVZSZXF4WkxrcHZFZ255ClFoSGEyakNYMTkxRStMZzB5S0NqamlsbW5FbDNJekY1UC9iV09mRll6WVhMYU9SbmVLbXpqT21rL1VtVUsrY1IKbGFTdDZrbkxlTDg2SkgwdTlsQUljeXZWMTRYdlFNTFJnWC9Dai9rQ2dZQnZEUHUxckdYYUVpTVpTWWdKay82RwpJN0JjdFFyMkFjQUtKQnNmWWFEanlpbkQ0Y3pVeDZPVGpLSzg3amZHUnYvVksyMnpCd3l0NUtVUEI2TjRLLzlVCnBiZXk4aGUzVFViM3p6d0p3amtEaFpBS0YwdHJES09QNlg1bThQUk90Zy9zWHRtQ1BCMHExSkVEc09hUkVqS3cKZE9GcUhxNFJ6VWlHTWpGZXZCSHNWdz09Ci0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-pv
  namespace: zabbix
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /data/zabbix  # Change this path if needed
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-pvc
  namespace: zabbix
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-db
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-db
  template:
    metadata:
      labels:
        app: zabbix-db
    spec:
      containers:
        - name: zabbix-db
          image: postgres:13
          env:
            - name: POSTGRES_DB
              value: "my_zabbix_db"  # Change this to your desired database name
            - name: POSTGRES_USER
              value: "my_user"  # Change this to your desired username
            - name: POSTGRES_PASSWORD
              value: "my_password"  # Change this to your desired password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: zabbix-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-db
  namespace: zabbix
spec:
  type: NodePort  # Ensure this is set to NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000  # Specify a port in the range 30000-32767
  selector:
    app: zabbix-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-server
          image: zabbix/zabbix-server-pgsql:latest
          env:
            - name: DB_SERVER_HOST
              value: "zabbix-db"  # Database service name
            - name: POSTGRES_USER
              value: "my_user"  # Same as above
            - name: POSTGRES_PASSWORD
              value: "my_password"  # Same as above
            - name: POSTGRES_DB
              value: "my_zabbix_db"  # Same as above
            - name: LISTEN_IP
              value: "0.0.0.0"  # Listen on all IPs
            - name: LISTEN_PORT
              value: "10051"  # Default Zabbix server port
            - name: DBHost
              value: "postgres"  # Database host
            - name: DBName
              value: "my_zabbix_db"  # Database name
            - name: DBUser
              value: "my_user"  # Database user
            - name: DBPassword
              value: "my_password"  # Database password
            - name: DBPort
              value: "5432"  # Database port
          ports:
            - containerPort: 10051
          volumeMounts:
            - name: zabbix-storage
              mountPath: /var/lib/zabbix
      volumes:
        - name: zabbix-storage
          persistentVolumeClaim:
            claimName: zabbix-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix
spec:
  type: NodePort  # Ensure this is set to NodePort
  ports:
    - port: 10051
      targetPort: 10051
      nodePort: 30051  # Specify a port in the range 30000-32767
  selector:
    app: zabbix-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web-nginx
  namespace: zabbix
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-web
  template:
    metadata:
      labels:
        app: zabbix-web
    spec:
      containers:
        - name: zabbix-web-nginx
          image: zabbix/zabbix-web-nginx-pgsql:latest
          env:
            - name: DB_SERVER_HOST
              value: "zabbix-db"  # Database service name
            - name: POSTGRES_USER
              value: "my_user"  # Same as above
            - name: POSTGRES_PASSWORD
              value: "my_password"  # Same as above
            - name: POSTGRES_DB
              value: "my_zabbix_db"  # Same as above
            - name: ZBX_SERVER_HOST
              value: "zabbix-server"
            - name: ZBX_SERVER_NAME
              value: "zabbix-server"  # Name of the Zabbix server
            - name: PHP_TZ
              value: "UTC"  # Set your timezone
          ports:
            - containerPort: 8080  # Default port for Zabbix web interface
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix
spec:
  type: NodePort  # Change to LoadBalancer if needed
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080  # Specify a port in the range 30000-32767
  selector:
    app: zabbix-web
